# 如果所有controller都没有命中，则使用默认的处理器，包括404，资源访问
# spring.resources.add-mappings=true
## 如果没有加  spring.resources.add-mappings=false（默认为true） 则加上这个也能触发 NoHandlerFoundException
#spring.mvc.static-path-pattern=/static/**
#spring:
#  mvc:
#    #如果没有相应的处理路径，不要直接跳转到错误页面，而是抛出 NoHandlerFoundException
#    throw-exception-if-no-handler-found: true
#  servlet:
#    multipart:
#      max-request-size: 50MB
#      max-file-size: 50MB

server:
  port: 8080
app:
  name: Anarres
  description: AnrDes

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/anarres?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
      username: root
      password: 123123
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ${app.name}
  profiles:
    active: dev

logging:
  level:
    root: info
    anarres:
      dao:
        log: debug



