server:
  port: 9090
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/anarres?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
      username: root
      password: 123123
      driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: ${app.name}

  profiles:
    active: dev

  task:
    thread-pool:
      work-queue-capacity: 10
      thread-name-prefix: Timer-Thread-
      scheduler-name-prefix: Timer-Scheduler-

logging:
  level:
    root: info
    anarres:
      dao:
        log: debug
